name: mac

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  mac-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore MajorsilenceReporting-Linux-GtkViewer.sln
      - name: Build GtkViewer
        run: dotnet build -c Release-DrawingCompat MajorsilenceReporting-Linux-GtkViewer.sln
      - name: Build MajorsilenceReporting DrawingCompat
        run: dotnet build -c Release-DrawingCompat MajorsilenceReporting.sln
      - name: Test
        run: dotnet test -c Release-DrawingCompat MajorsilenceReporting.sln --verbosity normal --collect:"XPlat Code Coverage" --logger:"trx"
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure() # run this step even if previous step failed
        with:
          name: unit tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx
